name: hallel
description: "Projeto mobile para a Comunidade Católica Hallel"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  dio: ^5.0.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  flutter_riverpod: ^2.1.2
  image_picker: ^0.8.6
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_hallel.png
    - assets/images/home_page_photo.svg
